"""PowerTrader-native strategy variable catalog for autoresearch."""

VARIABLE_CATALOG = [
    {
        'path': 'trade_start_level',
        'family': 'entry_gate',
        'title': 'Raise trade start level',
        'engine': 'powertrader_replay',
        'candidate_values': [4],
        'cause_ids': ['weak_entries', 'general_underperformance', 'fallback_1', 'fallback_2'],
    },
    {
        'path': 'start_allocation_pct',
        'family': 'allocation',
        'title': 'Adjust initial allocation size',
        'engine': 'powertrader_replay',
        'candidate_offsets': [-0.001, 0.0015],
        'min': 0.001,
        'max': 0.02,
        'cause_ids': ['drawdown_pressure', 'general_underperformance', 'fallback_1', 'fallback_2'],
    },
    {
        'path': 'dca_multiplier',
        'family': 'dca_aggression',
        'title': 'Adjust DCA multiplier',
        'engine': 'powertrader_replay',
        'candidate_offsets': [-0.3, 0.2],
        'min': 0.5,
        'max': 4.0,
        'cause_ids': ['dca_pressure', 'long_holds', 'general_underperformance', 'fallback_1', 'fallback_2'],
    },
    {
        'path': 'max_dca_buys_per_24h',
        'family': 'dca_frequency',
        'title': 'Adjust DCA rate limit',
        'engine': 'powertrader_replay',
        'candidate_values': [1, 3],
        'min': 0,
        'max': 6,
        'cause_ids': ['dca_pressure', 'general_underperformance', 'fallback_1', 'fallback_2'],
    },
    {
        'path': 'pm_start_pct_no_dca',
        'family': 'profit_target',
        'title': 'Adjust no-DCA profit trigger',
        'engine': 'powertrader_replay',
        'candidate_offsets': [-0.5, 0.5],
        'min': 1.0,
        'max': 12.0,
        'cause_ids': ['profit_giveback', 'long_holds', 'general_underperformance', 'fallback_1', 'fallback_2'],
    },
    {
        'path': 'pm_start_pct_with_dca',
        'family': 'profit_target',
        'title': 'Adjust post-DCA profit trigger',
        'engine': 'powertrader_replay',
        'candidate_offsets': [-0.5, 0.5],
        'min': 0.5,
        'max': 8.0,
        'cause_ids': ['profit_giveback', 'dca_pressure', 'general_underperformance', 'fallback_1', 'fallback_2'],
    },
    {
        'path': 'trailing_gap_pct',
        'family': 'trailing_gap',
        'title': 'Adjust trailing gap',
        'engine': 'powertrader_replay',
        'candidate_offsets': [-0.15, 0.15],
        'min': 0.1,
        'max': 3.0,
        'cause_ids': ['profit_giveback', 'long_holds', 'general_underperformance', 'fallback_1', 'fallback_2'],
    },
    {
        'path': 'dca_levels',
        'family': 'dca_ladder',
        'title': 'Adjust hard DCA ladder',
        'engine': 'powertrader_replay',
        'candidate_values': ['tighter', 'looser'],
        'cause_ids': ['dca_pressure', 'long_holds', 'general_underperformance', 'fallback_1', 'fallback_2'],
    },
]
